# 공시정보

# Step1: corp_code 불러오기

In [2]:
import os
from dotenv import load_dotenv

import requests
import zipfile
import io
import xml.etree.ElementTree as ET
import pandas as pd

load_dotenv()
API_KEY = os.getenv("DART_API_KEY")

url = "https://opendart.fss.or.kr/api/corpCode.xml"
params = {
    "crtfc_key": API_KEY
}

# 1) API 호출
response = requests.get(url, params=params, timeout=30)
response.raise_for_status()

# 2) ZIP 파일을 메모리에서 바로 열기
with zipfile.ZipFile(io.BytesIO(response.content)) as zf:
    xml_filename = zf.namelist()[0]
    with zf.open(xml_filename) as xml_file:
        xml_bytes = xml_file.read()

# 3) XML 파싱
root = ET.fromstring(xml_bytes)

rows = []
for item in root.findall("list"):
    rows.append({
        "corp_code": item.findtext("corp_code"),
        "corp_name": item.findtext("corp_name"),
        "corp_eng_name": item.findtext("corp_eng_name"),
        "stock_code": item.findtext("stock_code"),
        "modify_date": item.findtext("modify_date"),
    })

# 4) DataFrame으로 변환
df = pd.DataFrame(rows)

# 5) stock_code가 결측치가 아니고, 빈 문자열도 아닌 행만 남기기
df = df[df["stock_code"].notna() & (df["stock_code"].str.strip() != "")]
df

,corp_code,corp_name,corp_eng_name,stock_code,modify_date
1943,00260985,한빛네트,"HanbitNet, Inc.",036720,20170630
1955,00264529,엔플렉스,"Nplex,Inc.",040130,20170630
1956,00358545,동서정보기술,"Dong Seo Information Technology Co., Ltd.",055000,20170630
2694,00231567,애드모바일,,032600,20170630
3764,00359614,리더컴,"LEADER COMM.Co.,Ltd",056140,20170630
...,...,...,...,...,...
117222,00591441,어보브반도체,"ABOV Semiconductor Co.,Ltd.",102120,20251215
117223,00683007,엑스큐어,Xcure Corp.,070300,20251215
117257,01182408,소프트캠프,"SOFTCAMP CO., LTD",258790,20251031
117259,00600013,맵스리얼티,MIRAEASSET MAPS REALTY INVESTMENT COMPANY,094800,20251031
117283,00109693,DL,"DL Holdings CO.,LTD",000210,20250919

In [2]:
dup_rows = df[df["corp_name"].duplicated(keep=False)].sort_values("corp_name")
dup_rows

       corp_code corp_name             corp_eng_name stock_code modify_date
95188   00181712        SK                   SK Inc.     034730    20240328
31420   00144155        SK     SK Holdings Co., Ltd.     003600    20170630
23487   00104467      국민은행             Kookmin Bank      031150    20170630
98006   00386937      국민은행              KOOKMIN BANK     060000    20250102
38531   00925453      나무기술       NAMU TECH CO., LTD.     167380    20181211
...          ...       ...                       ...        ...         ...
95442   00159412      한국제지  HANKUK PAPER MFG CO.,LTD     002300    20240628
106198  00793155     핸디소프트           HANDYSOFT, Inc.     220180    20250910
4541    00231521     핸디소프트           HandySoft Corp.     032380    20170630
103272  01453670        휴럼           Hurum Co., Ltd.     353190    20240701
92887   01148909        휴럼           Hurum Co., Ltd.     284420    20240628

[68 rows x 5 columns]

# Step2: 기업개황

In [3]:
url = "https://opendart.fss.or.kr/api/company.json"
params = {
    "crtfc_key": API_KEY,
    "corp_code": "00144155"
}
response = requests.get(url, params=params, timeout=30)
response.json()

{'status': '000',
 'message': '정상',
 'corp_code': '00144155',
 'corp_name': 'SK(주)',
 'corp_name_eng': 'SK Holdings Co., Ltd.',
 'stock_name': 'SK',
 'stock_code': '003600',
 'ceo_nm': '조대식',
 'corp_cls': 'E',
 'jurir_no': '1101110022816',
 'bizr_no': '1168102054',
 'adres': '서울특별시 종로구  종로 26 (서린동)',
 'hm_url': 'www.sk.co.kr',
 'ir_url': '',
 'phn_no': '02-2121-0114',
 'fax_no': '02-2121-1891',
 'induty_code': '64992',
 'est_dt': '19621013',
 'acc_mt': '12'}

# Step3: 공시검색

In [3]:
url = "https://opendart.fss.or.kr/api/list.json"
params = {
    "crtfc_key": API_KEY,
    #"corp_code": "00126380",
    "bgn_de": "20260401",
    "end_de": "20260419",
    "page_no": 1,
    "page_count": 100,
    "last_reprt_at": "Y",
}
response = requests.get(url, params=params, timeout=30)
response.json()

{'status': '000',
 'message': '정상',
 'page_no': 1,
 'page_count': 100,
 'total_count': 40524,
 'total_page': 406,
 'list': [{'corp_code': '00498162',
   'corp_name': '한국주택금융공사',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '채권양도등의등록신청서[한국주택금융공사]',
   'rcept_no': '20260417000388',
   'flr_nm': '한국주택금융공사',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00498162',
   'corp_name': '한국주택금융공사',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '채권양도등의등록신청서[한국주택금융공사]',
   'rcept_no': '20260413001337',
   'flr_nm': '한국주택금융공사',
   'rcept_dt': '20260413',
   'rm': ''},
  {'corp_code': '00148504',
   'corp_name': '한국스탠다드차타드은행',
   'stock_code': '000110',
   'corp_cls': 'E',
   'report_nm': '이중상환청구권부채권등록신청서',
   'rcept_no': '20260415000195',
   'flr_nm': '한국스탠다드차타드은행',
   'rcept_dt': '20260415',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '일괄신고서(집합투자증권-신탁형)(한국투자JP모간미국테크증권자투자신탁(USD)(주식-재간접형))',
   'rcept_no': '20260409003132',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260409',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '일괄신고서(집합투자증권-신탁형)(한국투자JP모간미국테크증권자투자신탁UH(주식-재간접형))',
   'rcept_no': '20260409003055',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260409',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '일괄신고서(집합투자증권-신탁형)(한국투자JP모간미국테크증권자투자신탁H(주식-재간접형))',
   'rcept_no': '20260409003029',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260409',
   'rm': ''},
  {'corp_code': '00331478',
   'corp_name': '우리자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(우리선택과집중증권자투자신탁(주식))',
   'rcept_no': '20260417000377',
   'flr_nm': '우리자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00188380',
   'corp_name': '유진자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(유진챔피언공모주&배당주30증권투자신탁(채권혼합))',
   'rcept_no': '20260417000301',
   'flr_nm': '유진자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00241412',
   'corp_name': '교보악사자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(교보악사개인용MMF1호)',
   'rcept_no': '20260417000019',
   'flr_nm': '교보악사자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00241412',
   'corp_name': '교보악사자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(교보악사파워브릭스증권자투자신탁1호(주식))',
   'rcept_no': '20260417000022',
   'flr_nm': '교보악사자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00685935',
   'corp_name': '케이씨지아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]증권신고서(집합투자증권-신탁형)(KCGI코리아목표전환형증권투자신탁2호[채권혼합](운용전환일이후)KCGI코리아목표전환형증권투자신탁2호[채권])',
   'rcept_no': '20260417000462',
   'flr_nm': '케이씨지아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00685935',
   'corp_name': '케이씨지아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]증권신고서(집합투자증권-신탁형)(KCGI코리아목표전환형증권투자신탁3호[채권혼합](운용전환일이후)KCGI코리아목표전환형증권투자신탁3호[채권])',
   'rcept_no': '20260417000486',
   'flr_nm': '케이씨지아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00685935',
   'corp_name': '케이씨지아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]증권신고서(집합투자증권-신탁형)(KCGI코리아목표전환형증권투자신탁4호[채권혼합](운용전환일이후)KCGI코리아목표전환형증권투자신탁4호[채권])',
   'rcept_no': '20260417000528',
   'flr_nm': '케이씨지아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00685935',
   'corp_name': '케이씨지아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]증권신고서(집합투자증권-신탁형)(KCGI코리아목표전환형증권투자신탁5호[채권혼합](운용전환일이후)KCGI코리아목표전환형증권투자신탁5호[채권])',
   'rcept_no': '20260417000556',
   'flr_nm': '케이씨지아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00685935',
   'corp_name': '케이씨지아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]증권신고서(집합투자증권-신탁형)(KCGI코리아목표전환형증권투자신탁6호[채권혼합](운용전환일이후)KCGI코리아목표전환형증권투자신탁6호[채권])',
   'rcept_no': '20260417000576',
   'flr_nm': '케이씨지아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00685935',
   'corp_name': '케이씨지아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(KCGIESG동반성장증권자투자신탁[주식])',
   'rcept_no': '20260417000425',
   'flr_nm': '케이씨지아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00685935',
   'corp_name': '케이씨지아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(KCGI코리아퇴직연금증권자투자신탁[주식])',
   'rcept_no': '20260417000414',
   'flr_nm': '케이씨지아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00685935',
   'corp_name': '케이씨지아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(KCGI코리아증권투자신탁1호[주식])',
   'rcept_no': '20260417000403',
   'flr_nm': '케이씨지아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00685935',
   'corp_name': '케이씨지아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(KCGI코리아연금증권전환형자투자신탁1호[주식])',
   'rcept_no': '20260417000393',
   'flr_nm': '케이씨지아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00685935',
   'corp_name': '케이씨지아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-회사형)(케이씨지아이더우먼증권투자회사[주식])',
   'rcept_no': '20260417000382',
   'flr_nm': '케이씨지아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00685935',
   'corp_name': '케이씨지아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(KCGI코리아증권자투자신탁1호[채권])',
   'rcept_no': '20260417000375',
   'flr_nm': '케이씨지아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '01995042',
   'corp_name': '에이치피중일프로젝트유동화전문유한회사',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '자산양도등의등록신청서',
   'rcept_no': '20260416000165',
   'flr_nm': '교보증권',
   'rcept_dt': '20260416',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이FOCUS200증권상장지수투자신탁[주식])',
   'rcept_no': '20260417000256',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이FOCUSAI코리아액티브증권상장지수투자신탁[주식])',
   'rcept_no': '20260417000263',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이FOCUSESGLeaders150증권상장지수투자신탁[주식])',
   'rcept_no': '20260417000269',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이투게더인덱스증권자투자신탁1호[주식-파생형])',
   'rcept_no': '20260417000284',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이포트폴리오인덱스증권전환형자투자신탁1호[주식-파생형])',
   'rcept_no': '20260417000290',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이퇴직연금인덱스40증권자투자신탁1호[채권혼합-파생형])',
   'rcept_no': '20260417000308',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이인덱스플러스증권자투자신탁1호[주식-파생형])',
   'rcept_no': '20260417000314',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이굿초이스국공채증권투자신탁[채권])',
   'rcept_no': '20260417000319',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이1.5배레버리지인덱스증권자투자신탁[주식-파생형])',
   'rcept_no': '20260417000320',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이아시아넥스트인프라증권자투자신탁1호[주식])',
   'rcept_no': '20260417000322',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이적극성장장기소득공제증권자투자신탁[주식])',
   'rcept_no': '20260417000326',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이적극성장장기소득공제증권자투자신탁[채권혼합])',
   'rcept_no': '20260417000335',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이실적포커스15증권자투자신탁[채권혼합])',
   'rcept_no': '20260417000339',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-회사형)(브이아이루키10증권투자회사5호[채권혼합])',
   'rcept_no': '20260417000345',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이퇴직연금굿초이스증권자투자신탁1호[주식])',
   'rcept_no': '20260417000350',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이중국4차산업증권자투자신탁1호[주식])',
   'rcept_no': '20260417000360',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이퇴직연금중소형주플러스40증권자투자신탁1호[채권혼합])',
   'rcept_no': '20260417000368',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이FOCUSBABA-UST커버드콜혼합증권상장지수투자신탁[채권혼합-파생재간접형])',
   'rcept_no': '20260417000258',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00260514',
   'corp_name': '브이아이자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(브이아이FOCUSAI반도체위클리고정커버드콜증권상장지수투자신탁[주식-파생형])',
   'rcept_no': '20260417000248',
   'flr_nm': '브이아이자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자퇴직연금롱텀밸류40증권자투자신탁1호(채권혼합))',
   'rcept_no': '20260417000012',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자TDF알아서2015증권투자신탁(채권혼합-재간접형))',
   'rcept_no': '20260417000018',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자퇴직연금LCF2020증권자투자신탁1호(채권혼합))',
   'rcept_no': '20260417000023',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자삼성TOP3증권자투자신탁1호(채권혼합))',
   'rcept_no': '20260417000046',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자베트남그로스증권자투자신탁(주식))',
   'rcept_no': '20260417000049',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자네비게이터중국본토증권자투자신탁H(주식))',
   'rcept_no': '20260417000051',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자베트남그로스증권자투자신탁UH(주식))',
   'rcept_no': '20260417000052',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자네비게이터중국본토증권자투자신탁UH(주식))',
   'rcept_no': '20260417000057',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자미국S&P500동일가중모레드림증권자투자신탁UH(주식))',
   'rcept_no': '20260417000058',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자단기채플러스ESG증권투자신탁(채권))',
   'rcept_no': '20260417000059',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자SSGA글로벌저변동성증권자투자신탁H(주식))',
   'rcept_no': '20260417000062',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자KRX300인덱스증권투자신탁(주식))',
   'rcept_no': '20260417000063',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자SSGA글로벌저변동성증권자투자신탁UH(주식))',
   'rcept_no': '20260417000065',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자ACEAI반도체TOP3+증권상장지수투자신탁(주식))',
   'rcept_no': '20260417000071',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자삼성전자&하이닉스플러스증권투자신탁(주식))',
   'rcept_no': '20260417000074',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자MAN다이나믹인컴월배당증권자투자신탁(USD)(채권-재간접형))',
   'rcept_no': '20260417000066',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자신종개인연금적격TDF알아서2050증권전환형자투자신탁H(주식혼합-재간접형))',
   'rcept_no': '20260417000033',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자테크증권자투자신탁2호(주식))',
   'rcept_no': '20260417000246',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자테크증권자투자신탁1호(주식))',
   'rcept_no': '20260417000194',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00324548',
   'corp_name': '한국투자신탁운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한국투자신종개인용MMF5호)',
   'rcept_no': '20260417000010',
   'flr_nm': '한국투자신탁운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '01998298',
   'corp_name': '티월드제일백이십이차유동화전문유한회사',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '자산양도등의등록신청서',
   'rcept_no': '20260416000176',
   'flr_nm': 'SK텔레콤',
   'rcept_dt': '20260416',
   'rm': ''},
  {'corp_code': '00241388',
   'corp_name': '디비자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(DBNEW해오름신종MMF제3호)',
   'rcept_no': '20260416000108',
   'flr_nm': '디비자산운용',
   'rcept_dt': '20260416',
   'rm': ''},
  {'corp_code': '00241388',
   'corp_name': '디비자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(DB차이나본토RQFII증권자투자신탁(UH)[주식])',
   'rcept_no': '20260416000101',
   'flr_nm': '디비자산운용',
   'rcept_dt': '20260416',
   'rm': ''},
  {'corp_code': '00241388',
   'corp_name': '디비자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(DB차이나본토RQFII증권자투자신탁(H)[주식])',
   'rcept_no': '20260416000088',
   'flr_nm': '디비자산운용',
   'rcept_dt': '20260416',
   'rm': ''},
  {'corp_code': '00267526',
   'corp_name': '마이다스에셋자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(마이다스신성장기업포커스70청년형소득공제장기증권자투자신탁(주식))',
   'rcept_no': '20260417000447',
   'flr_nm': '마이다스에셋자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00267526',
   'corp_name': '마이다스에셋자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(마이다스뉴트렌드30증권자투자신탁(채권혼합))',
   'rcept_no': '20260417000446',
   'flr_nm': '마이다스에셋자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00267526',
   'corp_name': '마이다스에셋자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(마이다스퇴직연금거북이40증권자투자신탁1호(채권혼합))',
   'rcept_no': '20260417000365',
   'flr_nm': '마이다스에셋자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00267526',
   'corp_name': '마이다스에셋자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-회사형)(마이다스커버드콜증권투자회사(주식))',
   'rcept_no': '20260417000361',
   'flr_nm': '마이다스에셋자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00267526',
   'corp_name': '마이다스에셋자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(마이다스거북이70소득공제장기증권자투자신탁1호(주식))',
   'rcept_no': '20260417000359',
   'flr_nm': '마이다스에셋자산운용',
   'rcept_dt': '20260417',
   'rm': ''},
  {'corp_code': '00267526',
   'corp_name': '마이다스에셋자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(마이다스MIDAS코스피액티브증권상장지수투자신탁(주식))',
   'rcept_no': '20260416000423',
   'flr_nm': '마이다스에셋자산운용',
   'rcept_dt': '20260416',
   'rm': ''},
  {'corp_code': '00267526',
   'corp_name': '마이다스에셋자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(마이다스MIDAS일본테크액티브증권상장지수투자신탁(주식))',
   'rcept_no': '20260416000391',
   'flr_nm': '마이다스에셋자산운용',
   'rcept_dt': '20260416',
   'rm': ''},
  {'corp_code': '00267526',
   'corp_name': '마이다스에셋자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(마이다스MIDAS중소형액티브증권상장지수투자신탁(주식))',
   'rcept_no': '20260416000381',
   'flr_nm': '마이다스에셋자산운용',
   'rcept_dt': '20260416',
   'rm': ''},
  {'corp_code': '00243395',
   'corp_name': '한화자산운용',
   'stock_code': '',
   'corp_cls': 'E',
   'report_nm': '[기재정정]일괄신고서(집합투자증권-신탁형)(한화연금글로벌멀티인컴증권자투자신탁(주식혼합-재간접형))',
   'rcept_no': '20260415000366',
   'flr_nm': '한화자산운용',
   'rcept_dt': '20260415',
   'rm': ''},
  {'corp_code': '00243395',

# Step4: 공시서류원본파일

In [ ]:
import requests

url = "https://opendart.fss.or.kr/api/document.xml"
params = {
    "crtfc_key": API_KEY,
    "rcept_no": "20251231800604"
}

res = requests.get(url, params=params, timeout=30)
res.content

# with open("dart_original.zip", "wb") as f:
#     f.write(res.content)

# 정기보고서 주요정보

# Step1: 증자(감자) 현황

In [5]:
import requests

url = "https://opendart.fss.or.kr/api/irdsSttus.json"
params = {
    "crtfc_key": API_KEY,
    "corp_code": "00181712",
    "bsns_year": "2024",
    "reprt_code": "11011"
}

res = requests.get(url, params=params, timeout=30)
res.json()

{'status': '000',
 'message': '정상',
 'list': [{'rcept_no': '20250318001364',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'isu_dcrs_de': '-',
   'isu_dcrs_stle': '-',
   'isu_dcrs_stock_knd': '-',
   'isu_dcrs_qy': '-',
   'isu_dcrs_mstvdv_fval_amount': '-',
   'isu_dcrs_mstvdv_amount': '-',
   'stlm_dt': '2024-12-31'}]}

# Step2: 배당에 관한 사항

In [6]:
import requests

url = "https://opendart.fss.or.kr/api/alotMatter.json"
params = {
    "crtfc_key": API_KEY,
    "corp_code": "00181712",
    "bsns_year": "2023",
    "reprt_code": "11011"
}

res = requests.get(url, params=params, timeout=30)
res.json()

{'status': '000',
 'message': '정상',
 'list': [{'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '주당액면가액(원)',
   'thstrm': '200',
   'frmtrm': '200',
   'lwfr': '200',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '(연결)당기순이익(백만원)',
   'thstrm': '-776,798',
   'frmtrm': '1,098,683',
   'lwfr': '1,965,612',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '(별도)당기순이익(백만원)',
   'thstrm': '362,974',
   'frmtrm': '544,415',
   'lwfr': '1,499,764',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '(연결)주당순이익(원)',
   'thstrm': '-13,941',
   'frmtrm': '19,432',
   'lwfr': '37,010',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '현금배당금총액(백만원)',
   'thstrm': '276,469',
   'frmtrm': '280,149',
   'lwfr': '447,594',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '주식배당금총액(백만원)',
   'thstrm': '-',
   'frmtrm': '-',
   'lwfr': '-',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '(연결)현금배당성향(%)',
   'thstrm': '-',
   'frmtrm': '25.50',
   'lwfr': '22.80',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '현금배당수익률(%)',
   'stock_knd': '보통주',
   'thstrm': '2.60',
   'frmtrm': '2.50',
   'lwfr': '3.10',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '현금배당수익률(%)',
   'stock_knd': '우선주',
   'thstrm': '3.40',
   'frmtrm': '2.90',
   'lwfr': '3.60',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '주식배당수익률(%)',
   'stock_knd': '보통주',
   'thstrm': '-',
   'frmtrm': '-',
   'lwfr': '-',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '주식배당수익률(%)',
   'stock_knd': '우선주',
   'thstrm': '-',
   'frmtrm': '-',
   'lwfr': '-',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '주당 현금배당금(원)',
   'stock_knd': '보통주',
   'thstrm': '5,000',
   'frmtrm': '5,000',
   'lwfr': '8,000',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '주당 현금배당금(원)',
   'stock_knd': '우선주',
   'thstrm': '5,050',
   'frmtrm': '5,050',
   'lwfr': '8,050',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '주당 주식배당(주)',
   'stock_knd': '보통주',
   'thstrm': '-',
   'frmtrm': '-',
   'lwfr': '-',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '주당 주식배당(주)',
   'stock_knd': '우선주',
   'thstrm': '-',
   'frmtrm': '-',
   'lwfr': '-',
   'stlm_dt': '2023-12-31'}]}

# 주요사항보고서 주요정보

In [7]:
import requests

url = "https://opendart.fss.or.kr/api/mgRs.json"
params = {
    "crtfc_key": API_KEY,
    "corp_code": "00181712",
    "bgn_de": "20150101",
    "end_de": "20231231"
}

res = requests.get(url, params=params, timeout=30)
res.json()

{'status': '000',
 'message': '정상',
 'group': [{'title': '일반사항',
   'list': [{'rcept_no': '20150608000268',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'rpt_rcpn': '20150528000671',
     'stn': '흡수합병',
     'bddd': '2015년 04월 20일',
     'ctrd': '2015년 04월 20일',
     'gmtsck_shddstd': '2015년 05월 06일',
     'ap_gmtsck': '2015년 06월 26일',
     'aprskh_pd_bgd': '2015년 06월 26일',
     'aprskh_pd_edd': '2015년 07월 16일',
     'aprskh_prc': '에스케이씨앤씨 주식회사 기명식 보통주식: 230,940원\nSK주식회사 기명식 보통주식: 171,853원\nSK주식회사 기명식 우선주식: 114,536원',
     'mgdt_etc': '2015년 04월 21일\n2015년 06월 11일\n2015년 06월 27일\n2015년 06월 27일∼2015년 07월 27일\n2015년 06월 27일∼2015년 07월 31일\n2015년 08월 01일\n\n2015년 08월 03일\n\n2015년 08월 03일\n2015년 08월 03일\n2015년 08월 14일\n2015년 08월 17일',
     'rt_vl': '에스케이씨앤씨 주식회사 기명식 보통주 : SK주식회사 기명식 보통주 = 1 : 0.7367839\n에스케이씨앤씨 주식회사 기명식 우선주 : SK주식회사 기명식 우선주 =1 : 1.1102438',
     'exevl_int': "(1) 보통주 : 해당사항 없음\n\n(보통주의 경우 합병 당사 회사인 에스케이씨앤씨 주식회사와 SK주식회사 모두 유가증권시장주권상장법인이므로 '자본시장과금융투자업에관한법률' 시행령 제176조의5 제1항제1호에 의거하여 합병가액을 산정한 후, 이를 기초로 합병비율을 산정) \n\n(2) 우선주\n\n- 에스케이씨앤씨 주식회사 우선주 : 삼일회계법인\n- SK주식회사 우선주 : 유가증권시장에 ",
     'grtmn_etc': '합병주식의 교부와 단주 매각 대금 지급 외에는 별도의 합병 교부금 지급은 없습니다.'},
    {'rcept_no': '20210901000431',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'rpt_rcpn': '20210820000406',
     'stn': '흡수합병',
     'bddd': '2021년 08월 20일',
     'ctrd': '2021년 08월 23일',
     'gmtsck_shddstd': '2021년 09월 06일',
     'ap_gmtsck': '2021년 10월 29일',
     'aprskh_pd_bgd': '-',
     'aprskh_pd_edd': '-',
     'aprskh_prc': '-',
     'mgdt_etc': '2021년 08월 20일\n2021년 09월 06일\n2021년 09월 06일 ~ 2021년 09월 23일\n2021년 10월 29일\n2021년 10월 29일 ~ 2021년 11월 30일\n2021년 11월 30일\n2021년 12월 01일\n2021년 12월 01일\n2021년 12월 01일\n2021년 12월 07일\n2021년 12월 27일',
     'rt_vl': '1: 1.5778412\n(SK 주식회사 보통주 : SK머티리얼즈 주식회사 보통주)',
     'exevl_int': '해당사항 없음',
     'grtmn_etc': '합병 주식의 교부와 단주 매각 지급 외에는 별도의 합병 교부금 지급은 없습니다.'}]},
  {'title': '발행증권',
   'list': [{'rcept_no': '20150608000268',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'fv': '200',
     'slprc': '235,073',
     'slta': '6,196,602,794,382',
     'kndn': '기명식보통주',
     'cnt': '26,360,334'},
    {'rcept_no': '20210901000431',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'fv': '200',
     'slprc': '264,076',
     'slta': '1,574,653,234,804',
     'kndn': '기명식보통주',
     'cnt': '5,962,879'},
    {'rcept_no': '20150608000268',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'fv': '200',
     'slprc': '106,328',
     'slta': '60,196,002,280',
     'kndn': '기명식우선주',
     'cnt': '566,135'}]},
  {'title': '당사회사에관한사항',
   'list': [{'rcept_no': '20150608000268',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'cmpnm': '에스케이씨앤씨 주식회사',
     'sen': '존속회사',
     'tast': '5,307,039,000,000',
     'cpt': '10,000,000,000',
     'isstk_knd': '보통주',
     'isstk_cnt': '44,000,000'},
    {'rcept_no': '20210901000431',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'cmpnm': 'SK 주식회사',
     'sen': '존속회사',
     'tast': '25,306,014,000,000',
     'cpt': '15,385,000,000',
     'isstk_knd': '보통주',
     'isstk_cnt': '70,360,297'},
    {'rcept_no': '20150608000268',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'cmpnm': '에스케이씨앤씨 주식회사',
     'sen': '존속회사',
     'tast': '5,307,039,000,000',
     'cpt': '10,000,000,000',
     'isstk_knd': '우선주',
     'isstk_cnt': '-'},
    {'rcept_no': '20210901000431',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'cmpnm': 'SK 주식회사',
     'sen': '존속회사',
     'tast': '25,306,014,000,000',
     'cpt': '15,385,000,000',
     'isstk_knd': '우선주',
     'isstk_cnt': '566,135'},
    {'rcept_no': '20210901000431',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'cmpnm': 'SK머티리얼즈 주식회사',
     'sen': '소멸회사',
     'tast': '1,232,738,000,000',
     'cpt': '5,274,000,000',
     'isstk_knd': '보통주',
     'isstk_cnt': '10,547,673'},
    {'rcept_no': '20150608000268',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'cmpnm': 'SK주식회사',
     'sen': '소멸회사',
     'tast': '92,997,730,000,000',
     'cpt': '238,609,000,000',
     'isstk_knd': '보통주',
     'isstk_cnt': '46,961,812'},
    {'rcept_no': '20210901000431',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'cmpnm': 'SK머티리얼즈 주식회사',
     'sen': '소멸회사',
     'tast': '1,232,738,000,000',
     'cpt': '5,274,000,000',
     'isstk_knd': '우선주',
     'isstk_cnt': '-'},
    {'rcept_no': '20150608000268',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'cmpnm': 'SK주식회사',
     'sen': '소멸회사',
     'tast': '92,997,730,000,000',
     'cpt': '238,609,000,000',
     'isstk_knd': '우선주',
     'isstk_cnt': '509,920'}]}]}